# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import interdbclient
from interdbclient.api.info_infsourcetags_api import InfoInfsourcetagsApi  # noqa: E501
from interdbclient.rest import ApiException


class TestInfoInfsourcetagsApi(unittest.TestCase):
    """InfoInfsourcetagsApi unit test stubs"""

    def setUp(self):
        self.api = interdbclient.api.info_infsourcetags_api.InfoInfsourcetagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_info_infsourcetags_create(self):
        """Test case for info_infsourcetags_create

        """
        pass

    def test_info_infsourcetags_delete(self):
        """Test case for info_infsourcetags_delete

        """
        pass

    def test_info_infsourcetags_list(self):
        """Test case for info_infsourcetags_list

        """
        pass

    def test_info_infsourcetags_partial_update(self):
        """Test case for info_infsourcetags_partial_update

        """
        pass

    def test_info_infsourcetags_read(self):
        """Test case for info_infsourcetags_read

        """
        pass

    def test_info_infsourcetags_update(self):
        """Test case for info_infsourcetags_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
