# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import interdbclient
from interdbclient.api.prog_editions_api import ProgEditionsApi  # noqa: E501
from interdbclient.rest import ApiException


class TestProgEditionsApi(unittest.TestCase):
    """ProgEditionsApi unit test stubs"""

    def setUp(self):
        self.api = interdbclient.api.prog_editions_api.ProgEditionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_prog_editions_create(self):
        """Test case for prog_editions_create

        """
        pass

    def test_prog_editions_delete(self):
        """Test case for prog_editions_delete

        """
        pass

    def test_prog_editions_list(self):
        """Test case for prog_editions_list

        """
        pass

    def test_prog_editions_partial_update(self):
        """Test case for prog_editions_partial_update

        """
        pass

    def test_prog_editions_read(self):
        """Test case for prog_editions_read

        """
        pass

    def test_prog_editions_update(self):
        """Test case for prog_editions_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
