# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import interdbclient
from interdbclient.api.inter_proginfos_api import InterProginfosApi  # noqa: E501
from interdbclient.rest import ApiException


class TestInterProginfosApi(unittest.TestCase):
    """InterProginfosApi unit test stubs"""

    def setUp(self):
        self.api = interdbclient.api.inter_proginfos_api.InterProginfosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_inter_proginfos_create(self):
        """Test case for inter_proginfos_create

        """
        pass

    def test_inter_proginfos_delete(self):
        """Test case for inter_proginfos_delete

        """
        pass

    def test_inter_proginfos_list(self):
        """Test case for inter_proginfos_list

        """
        pass

    def test_inter_proginfos_partial_update(self):
        """Test case for inter_proginfos_partial_update

        """
        pass

    def test_inter_proginfos_read(self):
        """Test case for inter_proginfos_read

        """
        pass

    def test_inter_proginfos_update(self):
        """Test case for inter_proginfos_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
