# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import interdbclient
from interdbclient.api.prog_resources_api import ProgResourcesApi  # noqa: E501
from interdbclient.rest import ApiException


class TestProgResourcesApi(unittest.TestCase):
    """ProgResourcesApi unit test stubs"""

    def setUp(self):
        self.api = interdbclient.api.prog_resources_api.ProgResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_prog_resources_create(self):
        """Test case for prog_resources_create

        """
        pass

    def test_prog_resources_delete(self):
        """Test case for prog_resources_delete

        """
        pass

    def test_prog_resources_list(self):
        """Test case for prog_resources_list

        """
        pass

    def test_prog_resources_partial_update(self):
        """Test case for prog_resources_partial_update

        """
        pass

    def test_prog_resources_read(self):
        """Test case for prog_resources_read

        """
        pass

    def test_prog_resources_update(self):
        """Test case for prog_resources_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
