# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import interdbclient
from interdbclient.models.info_resource import InfoResource  # noqa: E501
from interdbclient.rest import ApiException


class TestInfoResource(unittest.TestCase):
    """InfoResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfoResource(self):
        """Test InfoResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = interdbclient.models.info_resource.InfoResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
