# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import interdbclient
from interdbclient.models.prog_resource import ProgResource  # noqa: E501
from interdbclient.rest import ApiException


class TestProgResource(unittest.TestCase):
    """ProgResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProgResource(self):
        """Test ProgResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = interdbclient.models.prog_resource.ProgResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
