# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import interdbclient
from interdbclient.api.prog_packagetags_api import ProgPackagetagsApi  # noqa: E501
from interdbclient.rest import ApiException


class TestProgPackagetagsApi(unittest.TestCase):
    """ProgPackagetagsApi unit test stubs"""

    def setUp(self):
        self.api = interdbclient.api.prog_packagetags_api.ProgPackagetagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_prog_packagetags_create(self):
        """Test case for prog_packagetags_create

        """
        pass

    def test_prog_packagetags_delete(self):
        """Test case for prog_packagetags_delete

        """
        pass

    def test_prog_packagetags_list(self):
        """Test case for prog_packagetags_list

        """
        pass

    def test_prog_packagetags_partial_update(self):
        """Test case for prog_packagetags_partial_update

        """
        pass

    def test_prog_packagetags_read(self):
        """Test case for prog_packagetags_read

        """
        pass

    def test_prog_packagetags_update(self):
        """Test case for prog_packagetags_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
