# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import interdbclient
from interdbclient.api.inter_infoinfos_api import InterInfoinfosApi  # noqa: E501
from interdbclient.rest import ApiException


class TestInterInfoinfosApi(unittest.TestCase):
    """InterInfoinfosApi unit test stubs"""

    def setUp(self):
        self.api = interdbclient.api.inter_infoinfos_api.InterInfoinfosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_inter_infoinfos_create(self):
        """Test case for inter_infoinfos_create

        """
        pass

    def test_inter_infoinfos_delete(self):
        """Test case for inter_infoinfos_delete

        """
        pass

    def test_inter_infoinfos_list(self):
        """Test case for inter_infoinfos_list

        """
        pass

    def test_inter_infoinfos_partial_update(self):
        """Test case for inter_infoinfos_partial_update

        """
        pass

    def test_inter_infoinfos_read(self):
        """Test case for inter_infoinfos_read

        """
        pass

    def test_inter_infoinfos_update(self):
        """Test case for inter_infoinfos_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
