# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import interdbclient
from interdbclient.models.infsource import Infsource  # noqa: E501
from interdbclient.rest import ApiException


class TestInfsource(unittest.TestCase):
    """Infsource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfsource(self):
        """Test Infsource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = interdbclient.models.infsource.Infsource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
