# coding: utf-8

# flake8: noqa

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from interdbclient.api.api_token_auth_api import ApiTokenAuthApi
from interdbclient.api.info_editions_api import InfoEditionsApi
from interdbclient.api.info_infsources_api import InfoInfsourcesApi
from interdbclient.api.info_infsourcetags_api import InfoInfsourcetagsApi
from interdbclient.api.info_resources_api import InfoResourcesApi
from interdbclient.api.inter_proginfos_api import InterProginfosApi
from interdbclient.api.prog_editions_api import ProgEditionsApi
from interdbclient.api.prog_packages_api import ProgPackagesApi
from interdbclient.api.prog_packagetags_api import ProgPackagetagsApi
from interdbclient.api.prog_resources_api import ProgResourcesApi

# import ApiClient
from interdbclient.api_client import ApiClient
from interdbclient.configuration import Configuration
# import models into sdk package
from interdbclient.models.auth_token import AuthToken
from interdbclient.models.info_edition import InfoEdition
from interdbclient.models.info_resource import InfoResource
from interdbclient.models.infsource import Infsource
from interdbclient.models.infsource_tag import InfsourceTag
from interdbclient.models.package import Package
from interdbclient.models.package_tag import PackageTag
from interdbclient.models.prog_edition import ProgEdition
from interdbclient.models.prog_info import ProgInfo
from interdbclient.models.prog_resource import ProgResource
