# coding: utf-8

# flake8: noqa
"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from interdbclient.models.auth_token import AuthToken
from interdbclient.models.info_edition import InfoEdition
from interdbclient.models.info_resource import InfoResource
from interdbclient.models.infsource import Infsource
from interdbclient.models.infsource_tag import InfsourceTag
from interdbclient.models.package import Package
from interdbclient.models.package_tag import PackageTag
from interdbclient.models.prog_edition import ProgEdition
from interdbclient.models.prog_info import ProgInfo
from interdbclient.models.prog_resource import ProgResource
