# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from interdbclient.configuration import Configuration


class Infsource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'formal_name': 'str',
        'clear_name': 'str',
        'human_description': 'str',
        'machine_description': 'str',
        'author_list': 'str',
        'supercategory': 'str',
        'category': 'str',
        'subcategory': 'str',
        'license_type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'formal_name': 'formal_name',
        'clear_name': 'clear_name',
        'human_description': 'human_description',
        'machine_description': 'machine_description',
        'author_list': 'author_list',
        'supercategory': 'supercategory',
        'category': 'category',
        'subcategory': 'subcategory',
        'license_type': 'license_type'
    }

    def __init__(self, id=None, name=None, formal_name=None, clear_name=None, human_description=None, machine_description=None, author_list=None, supercategory=None, category=None, subcategory=None, license_type=None, _configuration=None):  # noqa: E501
        """Infsource - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._formal_name = None
        self._clear_name = None
        self._human_description = None
        self._machine_description = None
        self._author_list = None
        self._supercategory = None
        self._category = None
        self._subcategory = None
        self._license_type = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        if formal_name is not None:
            self.formal_name = formal_name
        if clear_name is not None:
            self.clear_name = clear_name
        if human_description is not None:
            self.human_description = human_description
        if machine_description is not None:
            self.machine_description = machine_description
        if author_list is not None:
            self.author_list = author_list
        if supercategory is not None:
            self.supercategory = supercategory
        if category is not None:
            self.category = category
        if subcategory is not None:
            self.subcategory = subcategory
        if license_type is not None:
            self.license_type = license_type

    @property
    def id(self):
        """Gets the id of this Infsource.  # noqa: E501


        :return: The id of this Infsource.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Infsource.


        :param id: The id of this Infsource.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Infsource.  # noqa: E501


        :return: The name of this Infsource.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Infsource.


        :param name: The name of this Infsource.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def formal_name(self):
        """Gets the formal_name of this Infsource.  # noqa: E501


        :return: The formal_name of this Infsource.  # noqa: E501
        :rtype: str
        """
        return self._formal_name

    @formal_name.setter
    def formal_name(self, formal_name):
        """Sets the formal_name of this Infsource.


        :param formal_name: The formal_name of this Infsource.  # noqa: E501
        :type: str
        """

        self._formal_name = formal_name

    @property
    def clear_name(self):
        """Gets the clear_name of this Infsource.  # noqa: E501


        :return: The clear_name of this Infsource.  # noqa: E501
        :rtype: str
        """
        return self._clear_name

    @clear_name.setter
    def clear_name(self, clear_name):
        """Sets the clear_name of this Infsource.


        :param clear_name: The clear_name of this Infsource.  # noqa: E501
        :type: str
        """

        self._clear_name = clear_name

    @property
    def human_description(self):
        """Gets the human_description of this Infsource.  # noqa: E501


        :return: The human_description of this Infsource.  # noqa: E501
        :rtype: str
        """
        return self._human_description

    @human_description.setter
    def human_description(self, human_description):
        """Sets the human_description of this Infsource.


        :param human_description: The human_description of this Infsource.  # noqa: E501
        :type: str
        """

        self._human_description = human_description

    @property
    def machine_description(self):
        """Gets the machine_description of this Infsource.  # noqa: E501


        :return: The machine_description of this Infsource.  # noqa: E501
        :rtype: str
        """
        return self._machine_description

    @machine_description.setter
    def machine_description(self, machine_description):
        """Sets the machine_description of this Infsource.


        :param machine_description: The machine_description of this Infsource.  # noqa: E501
        :type: str
        """

        self._machine_description = machine_description

    @property
    def author_list(self):
        """Gets the author_list of this Infsource.  # noqa: E501


        :return: The author_list of this Infsource.  # noqa: E501
        :rtype: str
        """
        return self._author_list

    @author_list.setter
    def author_list(self, author_list):
        """Sets the author_list of this Infsource.


        :param author_list: The author_list of this Infsource.  # noqa: E501
        :type: str
        """

        self._author_list = author_list

    @property
    def supercategory(self):
        """Gets the supercategory of this Infsource.  # noqa: E501


        :return: The supercategory of this Infsource.  # noqa: E501
        :rtype: str
        """
        return self._supercategory

    @supercategory.setter
    def supercategory(self, supercategory):
        """Sets the supercategory of this Infsource.


        :param supercategory: The supercategory of this Infsource.  # noqa: E501
        :type: str
        """

        self._supercategory = supercategory

    @property
    def category(self):
        """Gets the category of this Infsource.  # noqa: E501


        :return: The category of this Infsource.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this Infsource.


        :param category: The category of this Infsource.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def subcategory(self):
        """Gets the subcategory of this Infsource.  # noqa: E501


        :return: The subcategory of this Infsource.  # noqa: E501
        :rtype: str
        """
        return self._subcategory

    @subcategory.setter
    def subcategory(self, subcategory):
        """Sets the subcategory of this Infsource.


        :param subcategory: The subcategory of this Infsource.  # noqa: E501
        :type: str
        """

        self._subcategory = subcategory

    @property
    def license_type(self):
        """Gets the license_type of this Infsource.  # noqa: E501


        :return: The license_type of this Infsource.  # noqa: E501
        :rtype: str
        """
        return self._license_type

    @license_type.setter
    def license_type(self, license_type):
        """Sets the license_type of this Infsource.


        :param license_type: The license_type of this Infsource.  # noqa: E501
        :type: str
        """

        self._license_type = license_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Infsource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Infsource):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Infsource):
            return True

        return self.to_dict() != other.to_dict()
