# coding: utf-8

"""
    InterDB API

    InterDB API  # noqa: E501

    OpenAPI spec version: v1
    Contact: meechanic.design@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from interdbclient.configuration import Configuration


class ProgInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'connection_kind': 'str',
        'prog_package': 'int',
        'info_infsource': 'int'
    }

    attribute_map = {
        'id': 'id',
        'connection_kind': 'connection_kind',
        'prog_package': 'prog_package',
        'info_infsource': 'info_infsource'
    }

    def __init__(self, id=None, connection_kind=None, prog_package=None, info_infsource=None, _configuration=None):  # noqa: E501
        """ProgInfo - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._connection_kind = None
        self._prog_package = None
        self._info_infsource = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if connection_kind is not None:
            self.connection_kind = connection_kind
        self.prog_package = prog_package
        self.info_infsource = info_infsource

    @property
    def id(self):
        """Gets the id of this ProgInfo.  # noqa: E501


        :return: The id of this ProgInfo.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProgInfo.


        :param id: The id of this ProgInfo.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def connection_kind(self):
        """Gets the connection_kind of this ProgInfo.  # noqa: E501


        :return: The connection_kind of this ProgInfo.  # noqa: E501
        :rtype: str
        """
        return self._connection_kind

    @connection_kind.setter
    def connection_kind(self, connection_kind):
        """Sets the connection_kind of this ProgInfo.


        :param connection_kind: The connection_kind of this ProgInfo.  # noqa: E501
        :type: str
        """

        self._connection_kind = connection_kind

    @property
    def prog_package(self):
        """Gets the prog_package of this ProgInfo.  # noqa: E501


        :return: The prog_package of this ProgInfo.  # noqa: E501
        :rtype: int
        """
        return self._prog_package

    @prog_package.setter
    def prog_package(self, prog_package):
        """Sets the prog_package of this ProgInfo.


        :param prog_package: The prog_package of this ProgInfo.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and prog_package is None:
            raise ValueError("Invalid value for `prog_package`, must not be `None`")  # noqa: E501

        self._prog_package = prog_package

    @property
    def info_infsource(self):
        """Gets the info_infsource of this ProgInfo.  # noqa: E501


        :return: The info_infsource of this ProgInfo.  # noqa: E501
        :rtype: int
        """
        return self._info_infsource

    @info_infsource.setter
    def info_infsource(self, info_infsource):
        """Sets the info_infsource of this ProgInfo.


        :param info_infsource: The info_infsource of this ProgInfo.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and info_infsource is None:
            raise ValueError("Invalid value for `info_infsource`, must not be `None`")  # noqa: E501

        self._info_infsource = info_infsource

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProgInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProgInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProgInfo):
            return True

        return self.to_dict() != other.to_dict()
